language: python
python:
  - "3.8"

services:
  - postgresql
  - postgis

env:
  - DJANGO_SETTINGS_MODULE=myproject.settings.test

before_install:
  - sudo apt-get update
  - sudo apt-get install -y binutils libproj-dev gdal-bin

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE myproject_test;" -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d myproject_test

script:
  - python manage.py test
